name: PostgreSQL 14 regression tests

on:
  pull_request:
    types: [opened, edited, reopened, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Append /usr/local/pgsql/bin to PATH
      run:  echo "/usr/local/pgsql/bin" >> $GITHUB_PATH
    - name: Uninstall Ubuntu's postgresql installation
      run:  sudo apt purge -y postgresql-14 postgresql-client-14 postgresql-client-common postgresql-common libpq-dev
    - name: Install build dependencies for postgresql
      run:  sudo apt-get install -y gcc python g++ libreadline-dev make ninja-build
    - name: Build and install postgresql 14.5
      run:  >
        cd ~ &&
        curl -O https://ftp.postgresql.org/pub/source/v14.5/postgresql-14.5.tar.gz &&
        tar xf postgresql-14.5.tar.gz &&
        cd postgresql-14.5 &&
        ./configure &&
        make &&
        sudo make install
    - name: Initialize postgresql database
      run:  >
        mkdir ~/data &&
        chmod -R 700 ~/data &&
        initdb -D ~/data &&
        pg_ctl -D ~/data start
    - uses: actions/checkout@v3
    - name: Compile pg_tle extension
      run:  make
    - name: Install pg_tle extension
      run:  sudo PATH=$PATH make install
    - name: Add pg_tle to shared_preload_libraries
      run:  >
        echo "shared_preload_libraries = 'pg_tle'" >> ~/data/postgresql.conf &&
        pg_ctl -D ~/data restart
    - name: Run pg_tle regression tests
      id:   regression-tests
      run:  make installcheck
    - name: Print regression.diffs if regression tests failed
      if:   failure() && steps.regression-tests.outcome != 'success'
      run:  cat regression.diffs
