name: test uni_api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: uninstall ubuntu's postgresql installation
      run:  sudo apt purge -y postgresql-14 postgresql-client-14 postgresql-client-common postgresql-common libpq-dev
    - name: install build dependencies for postgresql
      run:  sudo apt-get install -y gcc python g++ libreadline-dev make ninja-build bison flex
    - name: build and install postgresql 13.3
      run:  >
        git clone https://github.com/postgres/postgres.git &&
        cd postgres &&
        git checkout REL_13_3 &&
        ./configure --without-zlib &&
        make clean &&
        make -j &&
        sudo make install &&
        cd ..
    - name: initialize postgresql database
      run:  >
        export PATH=/usr/local/pgsql/bin:$PATH &&
        mkdir ~/data &&
        chmod -R 700 ~/data &&
        initdb -D ~/data &&
        pg_ctl -D ~/data start
    - uses: actions/checkout@v3
    - name: compile uni_api extension
      run:  >
        export PATH=/usr/local/pgsql/bin:$PATH &&
        cd uni_api &&
        USE_PGXS=1 make
    - name: install uni_api extension
      run:  >
        export PATH=/usr/local/pgsql/bin:$PATH &&
        cd uni_api &&
        sudo USE_PGXS=1 PATH=$PATH make install
    - name: add uni_api to shared_preload_libraries
      run:  >
        export PATH=/usr/local/pgsql/bin:$PATH &&
        echo "shared_preload_libraries = 'uni_api'" >> ~/data/postgresql.conf &&
        pg_ctl -D ~/data restart
    - name: run uni_api sql tests
      run:  >
        export PATH=/usr/local/pgsql/bin:$PATH &&
        cd uni_api &&
        USE_PGXS=1 make installcheck
