name: PostgreSQL 15 regression tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Append /usr/local/pgsql/bin to PATH
      run:  echo "/usr/local/pgsql/bin" >> $GITHUB_PATH
    - name: Uninstall Ubuntu's postgresql installation
      run:  sudo apt purge -y postgresql-14 postgresql-client-14 postgresql-client-common postgresql-common libpq-dev
    - name: Do an apt-get update
      run:  sudo apt-get update
    - name: Install build dependencies for postgresql
      run:  sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache libperl-dev
    - name: Install CPAN dependencies
      run:  sudo cpan -i "IPC::Run"
    - name: download postgresql
      run:  >
        cd ~ &&
        curl -O https://ftp.postgresql.org/pub/source/v15.1/postgresql-15.1.tar.gz &&
        curl -O https://ftp.postgresql.org/pub/source/v15.1/postgresql-15.1.tar.gz.sha256
    - name: verify postgresql
      run:  >
        cd ~ &&
        sha256sum --check postgresql-15.1.tar.gz.sha256
    - name: build postgresql
      run:  >
        cd ~ &&
        tar xzf postgresql-15.1.tar.gz &&
        cd postgresql-15.1 &&
        ./configure --enable-tap-tests --enable-cassert --enable-debug --with-openssl --with-perl &&
        make &&
        sudo PATH=$PATH make install &&
        cd contrib && make && sudo PATH=$PATH make install &&
        cd ../src/test/perl && sudo PATH=$PATH make install
    - name: initialize postgresql database
      run:  >
        mkdir ~/data &&
        chmod -R 700 ~/data &&
        initdb -D ~/data &&
        pg_ctl -D ~/data start
    - uses: actions/checkout@v3
    - name: Compile pg_tle extension
      run:  make
    - name: Install pg_tle extension
      run:  sudo PATH=$PATH make install
    - name: Add pg_tle to shared_preload_libraries
      run:  >
        echo "shared_preload_libraries = 'pg_tle'" >> ~/data/postgresql.conf
    - name: Restart postgresql
      run:  pg_ctl -D ~/data restart
    - name: Run pg_tle regression tests
      id:   regression-tests
      run:  PERL5LIB="${HOME}/postgresql-15.1/src/test/perl:${PERL5LIB}" make installcheck
    - name: Print regression.diffs if regression tests failed
      if:   failure() && steps.regression-tests.outcome != 'success'
      run:  cat regression.diffs
