name: PostgreSQL 14 regression tests

on:
  pull_request:
    types: [opened, edited, reopened, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add PGDG apt repository and install postgresql-14 with header files
      run:  >
        sudo apt-get install -y curl ca-certificates gnupg &&
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null &&
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' &&
        sudo apt-get update &&
        sudo apt-get install -y postgresql-14 postgresql-server-dev-14
    - name: Start postgresql
      run:  sudo systemctl start postgresql
    - name: Create postgres superuser for runner
      run:  sudo -u postgres createuser -s -w runner
    - uses: actions/checkout@v3
    - name: Compile pg_tle extension
      run:  make
    - name: Install pg_tle extension
      run:  sudo make install
    - name: Add pg_tle to shared_preload_libraries
      run:  sudo sh -c "echo 'shared_preload_libraries = '\''pg_tle'\' >> /etc/postgresql/14/main/postgresql.conf"
    - name: Restart postgresql
      run:  sudo systemctl restart postgresql
    - name: Run pg_tle regression tests
      id:   regression-tests
      run:  make installcheck
    - name: Print regression.diffs if regression tests failed
      if:   failure() && steps.regression-tests.outcome != 'success'
      run:  cat regression.diffs
