name: test uni-api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install postgresql from apt repository
      run: sudo apt install postgresql-common && sudo sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
    - uses: actions/checkout@v3
    - name: cd uni-api
      run: cd uni-api
    - name: make install
      run: make install
    - name: make installcheck
      run: make installcheck
